2019-02-13 11:48:52.767 ERROR 5 BA.IMIS.Common.Shared - System.Exception: {"ResultMessage":"Not Found","ResultData":null}
   at BA.IMIS.Common.Shared.GetMyrcene(String endPoint) in C:\Users\mike.BA\Source\Repos\BA.iMIS.Common\Common.cs:line 375
2019-02-13 11:48:54.264 ERROR 5 BA.IMIS.Common.Shared - System.Exception: {"ResultMessage":"Not Found","ResultData":null}
   at BA.IMIS.Common.Shared.GetMyrcene(String endPoint) in C:\Users\mike.BA\Source\Repos\BA.iMIS.Common\Common.cs:line 375
2019-02-13 11:54:52.977 ERROR 8 BA.IMIS.Common.Shared - System.Exception: {"ResultMessage":"Duplicate username found","ResultData":null}
   at BA.IMIS.Common.Shared.PostMyrcene[T](String endpoint, T obj) in C:\Users\mike.BA\Source\Repos\BA.iMIS.Common\Common.cs:line 414
