2019-02-22 11:57:58.779 ERROR 9 BA.IMIS.Common.Shared - System.Exception: {"ResultMessage":"Not Found","ResultData":null}
   at BA.IMIS.Common.Shared.GetMyrcene(String endPoint) in C:\Users\mike.BA\Source\Repos\BA.iMIS.Common\Common.cs:line 375
2019-02-22 11:57:59.546 ERROR 9 BA.IMIS.Common.Shared - System.Exception: {"ResultMessage":"Not Found","ResultData":null}
   at BA.IMIS.Common.Shared.GetMyrcene(String endPoint) in C:\Users\mike.BA\Source\Repos\BA.iMIS.Common\Common.cs:line 375
2019-02-22 12:01:11.929 ERROR 9 BA.IMIS.Common.Shared - System.Exception: {"ResultMessage":"Duplicate username found","ResultData":null}
   at BA.IMIS.Common.Shared.PostMyrcene[T](String endpoint, T obj) in C:\Users\mike.BA\Source\Repos\BA.iMIS.Common\Common.cs:line 414
2019-02-22 12:01:58.791 ERROR 9 BA.IMIS.Common.Shared - System.Exception: {"ResultMessage":"Duplicate username found","ResultData":null}
   at BA.IMIS.Common.Shared.PostMyrcene[T](String endpoint, T obj) in C:\Users\mike.BA\Source\Repos\BA.iMIS.Common\Common.cs:line 414
2019-02-22 12:03:11.967 ERROR 6 BA.IMIS.Common.Shared - System.Exception: {"ResultMessage":"Not Found","ResultData":null}
   at BA.IMIS.Common.Shared.GetMyrcene(String endPoint) in C:\Users\mike.BA\Source\Repos\BA.iMIS.Common\Common.cs:line 375
2019-02-22 12:03:12.661 ERROR 7 BA.IMIS.Common.Shared - System.Exception: {"ResultMessage":"Not Found","ResultData":null}
   at BA.IMIS.Common.Shared.GetMyrcene(String endPoint) in C:\Users\mike.BA\Source\Repos\BA.iMIS.Common\Common.cs:line 375
2019-02-22 12:04:12.682 ERROR 6 BA.IMIS.Common.Shared - System.Exception: {"ResultMessage":"Duplicate username found","ResultData":null}
   at BA.IMIS.Common.Shared.PostMyrcene[T](String endpoint, T obj) in C:\Users\mike.BA\Source\Repos\BA.iMIS.Common\Common.cs:line 414
2019-02-22 12:14:25.008 ERROR 6 BA.IMIS.Common.Shared - System.Exception: {"ResultMessage":"Not Found","ResultData":null}
   at BA.IMIS.Common.Shared.GetMyrcene(String endPoint) in C:\Users\mike.BA\Source\Repos\BA.iMIS.Common\Common.cs:line 375
2019-02-22 12:14:25.703 ERROR 7 BA.IMIS.Common.Shared - System.Exception: {"ResultMessage":"Not Found","ResultData":null}
   at BA.IMIS.Common.Shared.GetMyrcene(String endPoint) in C:\Users\mike.BA\Source\Repos\BA.iMIS.Common\Common.cs:line 375
2019-02-22 13:10:38.617 ERROR 6 BA.IMIS.Common.Shared - System.Exception: {"ResultMessage":"Not Found","ResultData":null}
   at BA.IMIS.Common.Shared.GetMyrcene(String endPoint) in C:\Users\mike.BA\Source\Repos\BA.iMIS.Common\Common.cs:line 375
2019-02-22 13:10:39.307 ERROR 7 BA.IMIS.Common.Shared - System.Exception: {"ResultMessage":"Not Found","ResultData":null}
   at BA.IMIS.Common.Shared.GetMyrcene(String endPoint) in C:\Users\mike.BA\Source\Repos\BA.iMIS.Common\Common.cs:line 375
2019-02-22 13:13:12.892 ERROR 6 BA.IMIS.Common.Shared - System.Threading.ThreadAbortException: Thread was being aborted.
   at System.Diagnostics.Debugger.CustomNotification(ICustomDebuggerNotification data)
   at System.Diagnostics.Debugger.NotifyOfCrossThreadDependencySlow()
   at System.Diagnostics.Debugger.NotifyOfCrossThreadDependency()
   at System.Threading.Tasks.Task.InternalWait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at BA.IMIS.Common.Shared.GetMyrcene(String endPoint) in C:\Users\mike.BA\Source\Repos\BA.iMIS.Common\Common.cs:line 370
2019-02-22 13:21:42.938 ERROR 6 BA.IMIS.Common.Shared - System.Exception: {"ResultMessage":"Not Found","ResultData":null}
   at BA.IMIS.Common.Shared.GetMyrcene(String endPoint) in C:\Users\mike.BA\Source\Repos\BA.iMIS.Common\Common.cs:line 375
2019-02-22 13:21:43.683 ERROR 7 BA.IMIS.Common.Shared - System.Exception: {"ResultMessage":"Not Found","ResultData":null}
   at BA.IMIS.Common.Shared.GetMyrcene(String endPoint) in C:\Users\mike.BA\Source\Repos\BA.iMIS.Common\Common.cs:line 375
