2019-02-20 17:10:36.259 ERROR 5 BA.IMIS.Common.Shared - System.Exception: {"ResultMessage":"Not Found","ResultData":null}
   at BA.IMIS.Common.Shared.GetMyrcene(String endPoint) in C:\Users\mike.BA\Source\Repos\BA.iMIS.Common\Common.cs:line 375
2019-02-20 17:10:42.300 ERROR 6 BA.IMIS.Common.Shared - System.Exception: {"ResultMessage":"Not Found","ResultData":null}
   at BA.IMIS.Common.Shared.GetMyrcene(String endPoint) in C:\Users\mike.BA\Source\Repos\BA.iMIS.Common\Common.cs:line 375
